import FacebookIcon from "@mui/icons-material/Facebook";
import TwitterIcon from "@mui/icons-material/Twitter";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import YouTubeIcon from "@mui/icons-material/YouTube";
import InstagramIcon from "@mui/icons-material/Instagram";

export const RightListItems = [
  {
    id: 101,
    title: "دوربین مدار بسته",
    link: "/cctv",
    subMenu: [
      {
        id: 102,
        title: "دوربین داهوا",
        link: "/cctv/adahua",
      },
      {
        id: 103,
        title: "دوربین بولت",
        link: "/cctv/bullet",
      },
      {
        id: 104,
        title: "دوربین اسپید دام",
        link: "/cctv/dom",
      },
      {
        id: 105,
        title: "دستگاه DVR",
        link: "/cctv/dvr",
      },
    ],
  },
  {
    id: 106,
    title: "آیفون تصویری",
    link: "/videodoorphone",
    subMenu: [
      {
        id: 107,
        title: "سیماران",
        link: "/videodoorphone/simaran",
      },
      {
        id: 108,
        title: "کالیوز",
        link: "/videodoorphone/calluse",
      },
      {
        id: 109,
        title: "تکنما",
        link: "/videodoorphone/taknama",
      },
      {
        id: 110,
        title: "سوزوکی",
        link: "/videodoorphone/suzuki",
      },
    ],
  },
  {
    title: "جک درب پارکینگی",
    link: "/automaticgate",
    subMenu: [],
  },

  {
    title: "کرکره برقی",
    link: "/rolling-shutters",
    subMenu: [],
  },
];
export const TopCardsInfo = [
  {
    id: 111,
    title: "آیفون تصویری تابا 1040M صفحه نمایش 4.3 اینچ",
    image: "/image/taba-1040-video-cover-2.jpg",
    alt: "عکس نارنجی رنگ به همراه آیفون تصویری تابا TVD-1040M200",
    link: "/video-door-phone/taba/taba-1040m",
    view: "193",
  },
  {
    id: 112,
    title: "آیفون تصویری تابا 1043 با حافظه",
    image: "/image/tvd-1043I.jpg",
    alt: "عکس آبی رنگ معرفی آیفون تصویری تابا 1043",
    link: "/video-door-phone/taba/taba-1043",
    view: "131",
  },
  {
    id: 113,
    title: "دوربین آیمو کروزر دوال Imou dual cruiser",
    image: "/image/Imou-dual-cruiser.jpg",
    alt: "عکس دوربین IMou ",
    link: "/cctv/imou-cctv/Imou-dual-cruiser",
    view: "104",
  },
];
export const CategoryItems = [
  {
    id: 114,
    title: "آیفون تصویری",
    image: "/image/branches-banner/taba-1040-video-cover.jpg",
    alt: "بنر نارنجی رنگ به همراه آیفون تصویری تابا TVD-1040M200",
    link: "/video-door-phone/taba/taba-1040m",
    description: "معرفی آیفون تصویری اقتصادی تابا 1040M",
  },
  {
    id: 115,
    title: "دوربین مدار بسته",
    image: "/image/branches-banner/imou-cruiser-video-cover.jpg",
    alt: "بنر نارنجی رنگ معرفی دوربین مدار بسته آیمو مدل cruiser",
    link: "/cctv/imou-cctv/Imou-dual-cruiser",
    description: "معرفی دوربین آیمو با دو لنز مجزا",
  },
  {
    id: 116,
    title: "جک درب پارکینگ",
    image: "/image/branches-banner/automatic-gate-suzuki-sz400.jpg",
    alt: "بنر سبز رنگ نمونه کارکرد جک سوزوکی sz400",
    link: "/automatic-gate/suzuki-sz400",
    description: "معرفی جک پارکینگ سوزوکی sz400",
  },
  {
    id: 117,
    title: "کرکره برقی",
    image: "/image/branches-banner/rolling-shutter-for-windows.jpg",
    alt: "کرکره برقی برای منازل مورد استفاده در گلدان",
    link: "/automatic-gate/suzuki-sz400",
    description: "معرفی ویدویی انواع کرکره برقی",
  },
];
export const NewVideosItems = [
  {
    id: 118,
    image: "/image/new-videos-images/taba-4070-video-cover-2.jpg",
    alt: "عکس صورتی رنگ آیفون تصویری تابا 4070",
    link: "/video-door-phone/taba/taba-4070",
    description: "آیفون تصویری تابا 4070",
  },
  {
    id: 119,
    image: "/image/new-videos-images/73m-simaran.jpg",
    alt: "عکس آبی رنگ معرفی آیفون تصویری تابا HS-73/M200",
    link: "/video-door-phone/simaran/73M",
    description: "آیفون سیماران 73M حافظه دار",
  },
  {
    id: 120,
    image: "/image/new-videos-images/hs-78-m100-wifi.jpg",
    alt: "عکس بنفش رنگ معرفی آیفون تصویری HS-78/M100-Wifi",
    link: "/video-door-phone/simaran/hs-78w",
    description: "آیفون تصویری سیماران Hs-78W وای فای دار",
  },
  {
    id: 121,
    image: "/image/new-videos-images/simaran-46tkm.jpg",
    alt: "عکس آبی و سیاه آیفون تصویری سیماران HS-46TKM",
    link: "/video-door-phone/simaran/46tkm",
    description: "آیفون تصویری سیماران Hs-46TKM",
  },
  {
    id: 122,
    image: "/image/new-videos-images/simaran-hs-43tkm100-video-cover.jpg",
    alt: " HS-43TKM100 عکس معرفی آیفون تصویری سیماران",
    link: "/video-door-phone/simaran/hs-43tkm",
    description: "آیفون تصویری سیماران Hs-43TKM",
  },
];
export const TrainingItems = [
  {
    id: 123,
    image: "/image/training-images/tvd-1090-m200.jpg",
    alt: "عکس قرمز رنگ معرفی آیفون تصویری تابا مدل 1090",
    link: "/video-door-phone/taba/1090m",
    description: "آیفون تصویری تابا 1090",
  },
  {
    id: 124,
    image: "/image/training-images/hs-72tk-m100.jpg",
    alt: "عکس آبی رنگ آیفون تصویری سیماران مدل HS-72TK/M100",
    link: "/video-door-phone/simaran/hs-43tkm",
    description: "آیفون تصویری Hs-72TKM سیماران",
  },
  {
    id: 125,
    image: "/image/training-images/taba-4070-video-cover-2.jpg",
    alt: "کارت معرفی آموزش آیفون تصویری تابا",
    link: "/video-door-phone/taba/taba-4070m",
    description: "آیفون تصویری تابا 4070M",
  },
];

export const SocialMediaItems = [
  {
    id: 126,
    link: "/",
    icon: <TwitterIcon sx={{ color: "#fff", fontSize: "3rem" }} />,
  },
  {
    id: 127,
    link: "/",
    icon: <FacebookIcon sx={{ color: "#fff", fontSize: "3rem" }} />,
  },
  {
    id: 128,
    link: "/",
    icon: <LinkedInIcon sx={{ color: "#fff", fontSize: "3rem" }} />,
  },
  {
    id: 129,
    link: "/",
    icon: <YouTubeIcon sx={{ color: "#fff", fontSize: "3rem" }} />,
  },
  {
    id: 130,
    link: "/",
    icon: <InstagramIcon sx={{ color: "#fff", fontSize: "3rem" }} />,
  },
];
export const CategoriesItemCard = [
  {
    id: 131,
    image: "/image/category-items/electropeyk-592-video-cover2.jpg",
    alt: "عکس آبی معرفی آیفون تصویری الکتروپیک New 592",
    link: "/product",
    description: "آیفون تصویری الکتروپیک 592",
    realsedate: "22 اسفند 1402",
    view: "13",
  },
  {
    id: 132,
    image: "/image/category-items/electropeyk-797.jpg",
    alt: "آیفون تصویری الکترو پیک مدل 797",
    link: "/product",
    description: "آیفون تصویری 797 الکتروپیک",
    realsedate: "22 اسفند 1402",
    view: "14",
  },
  {
    id: 133,
    image: "/image/category-items/taba-1040-video-cover-2.jpg",
    alt: "عکس با بک گراند نارنجی آیفون تصویری تابا 1040M صفحه نمایش 4.3 اینچ",
    link: "/product",
    description: "آیفون تصویری تابا 1040M صفحه نمایش 4.3 اینچ",
    realsedate: "22 اسفند 1402",
    view: "200",
  },
  {
    id: 134,
    image: "/image/category-items/tvd-1035.jpg",
    alt: "عکس سبز رنگ معرفی ویدیویی آیفون تصویری تابا 1035",
    link: "/product",
    description: "بررسی ویدیویی آیفون تصویری تابا 1035",
    realsedate: "22 اسفند 1402",
    view: "26",
  },
  {
    id: 135,
    image: "/image/category-items/tvd-1090-m200.jpg",
    alt: "بنر قرمز رنگ آیفون تصویری تابا 1090",
    link: "/product",
    description: "آیفون تصویری تابا 1090",
    realsedate: "22 اسفند 1402",
    view: "7",
  },
  {
    id: 136,
    image: "/image/category-items/electropeyk-1096.jpg",
    alt: "بنر سبز رنگ معرفی آیفون تصویری الکتروپیک 1096",
    link: "/product",
    description: "آیفون تصویری الکتروپیک 1096",
    realsedate: "22 اسفند 1402",
    view: "29",
  },
  {
    id: 137,
    image: "/image/category-items/vdp-1096-peyk.jpg",
    alt: "عکس دو رنگ معرفی موشن گرافی آیفون تصویری الکتروپیک 1096",
    link: "/product",
    description: "موشن گرافی آیفون تصویری الکتروپیک 1096",
    realsedate: "22 اسفند 1402",
    view: "26",
  },
  {
    id: 138,
    image: "/image/category-items/install-one-unit-elektropeyk.jpg",
    alt: "عکس آبی رنگ روش نصب آیفون تصویری الکتروپیک 1 واحدی",
    link: "/product",
    description: "روش نصب آیفون تصویری الکتروپیک 1 واحدی",
    realsedate: "22 اسفند 1402",
    view: "53",
  },
  {
    id: 139,
    image: "/image/category-items/electropeyk-592-video-cover2.jpg",
    alt: "عکس آبی رنگ معرفی آیفون تصویری الکتروپیک 592",
    link: "/product",
    description: "آیفون تصویری الکتروپیک 592",
    realsedate: "22 اسفند 1402",
    view: "13",
  },
  {
    id: 140,
    image: "/image/category-items/electropeyk-897.jpg",
    alt: "عکس نارنجی معرفی آیفون تصویری 897 الکتروپیک بدون حافظه",
    link: "/product",
    description: "آیفون تصویری 897 الکتروپیک بدون حافظه",
    realsedate: "22 اسفند 1402",
    view: "9",
  },
  {
    id: 141,
    image: "/image/category-items/electropeyk-797.jpg",
    alt: "عکس بنفش رنگ معرفی آیفون تصویری 797 الکتروپیک",
    link: "/product",
    description: "آیفون تصویری 797 الکتروپیک",
    realsedate: "22 اسفند 1402",
    view: "14",
  },
  {
    id: 142,
    image: "/image/category-items/electropeyk-1294.jpg",
    alt: "بنر قهوه ای رنگ معرفی آیفون تصویری الکتروپیک 1294",
    link: "/product",
    description: "آیفون تصویری الکتروپیک 1294",
    realsedate: "22 اسفند 1402",
    view: "14",
  },
  {
    id: 143,
    image: "/image/category-items/electropeyk-996.jpg",
    alt: "بنر قهوه ای رنگ معرفی آیفون تصویری الکتروپیک 996",
    link: "/product",
    description: "آیفون تصویری الکتروپیک 996",
    realsedate: "22 اسفند 1402",
    view: "13",
  },
  {
    id: 144,
    image: "/image/category-items/automatic-gate-opener-vdp-electropeyk.jpg",
    alt: "بنر با پس زمینه آبی معرفی باز کردن درب پارکینگ با آیفون تصویری الکتروپیک",
    link: "/product",
    description: "باز کردن درب پارکینگ با آیفون تصویری الکتروپیک",
    realsedate: "22 اسفند 1402",
    view: "4",
  },
  {
    id: 145,
    image: "/image/category-items/simaran-76tkm.jpg",
    alt: "عکس دو رنگ آیفون تصویری سیماران 76tkm",
    link: "/product",
    description: "آیفون سیماران Hs-76TKM",
    realsedate: "22 اسفند 1402",
    view: "84",
  },
  {
    id: 146,
    image: "/image/category-items/taba-4070-video-cover-2.jpg",
    alt: "عکس صورتی رنگ TVD-4070",
    link: "/product",
    description: " 02 فروردین 1403",
    realsedate: "22 اسفند 1402",
    view: "17",
  },
];
export const ProductNextItems = [
  {
    id: 147,
    image: "/image/next-videos/dahua-warm-light-pack.jpg",
    alt: "بنر معرفی دوربین مدار بسته وارم لایت",
    link: "/product",
    description: "دوربین های مدار بسته وارم لایت",
  },
  {
    id: 148,
    image: "/image/next-videos/install-one-unit-elektropeyk.jpg",
    alt: "بنر معرفی روش نصب آیفون تصویری",
    link: "/product",
    description: "نصب آیفون تصویری الکتروپیک",
  },
  {
    id: 149,
    image: "/image/next-videos/simaran-76tkm.jpg",
    alt: "بنر آیفون تصویری سیماران 76",
    link: "/product",
    description: "ویدیو بررسی آیفون تصویری سیماران مدل 76tk",
  },
  {
    id: 150,
    image: "/image/next-videos/simaran-46tk-video-cover-2.jpg",
    alt: "بنر آیفون تصویری سیماران 46",
    link: "/product",
    description: "ویدیو بررسی آیفون تصویری سیماران مدل 46tk",
  },
];
export const RelatedVideos = [
  {
    id: 151,
    link: "/product",
    image: "/image/next-videos/simaran-46tk-video-cover-2.jpg",
    alt: "ویدئوی مرتبط سیماران 46",
    title: "بررسی آیفون تصویری سیماران مدل 46",
    relesedate: "06 دی 1402",
    view: "654",
  },
  {
    id: 152,
    link: "/product",
    image: "/image/next-videos/simaran-76tkm.jpg",
    alt: "ویدیوی مرتبط سیماران 76",
    title: "بررسی آیفون تصویری سیماران مدل 76",
    relesedate: "06 دی 1402",
    view: "654",
  },
  {
    id: 153,
    link: "/product",
    image: "/image/next-videos/install-one-unit-elektropeyk.jpg",
    alt: "نصب آیفون تصویری الکتروپیک",
    title: "بررسی آیفون تصویری سیماران مدل 76",
    relesedate: "06 دی 1402",
    view: "654",
  },
];
